language: python

python:
  - "3.7-dev"

services:
  - docker

env:
  global:
    #Production aws key
    - AWS_ACCESS_KEY_ID=AKIA4TXB7QOHH4GTVXZF
    #Production secret key: travis encrypt AWS_SECRET_ACCESS_KEY=<SECRET_KEY>
    - secure: aBpFZ7VNBQtE683M03tMTmoG6K0eIr5GCCZ23sskHaleDGDKZWimqoBMZtNEdZwLTZU5Ul07eVBA4yuem05Wz9YIE079wGLW6jkjiELyGnqgIoYioWzihaabC6P4VFgvdKw+hZhKEiuJtBqCQIgadyqW0dcZ3kJME1EQYBfCAB9fEDD34PIoMilQKQKCtRPJzZFR9lpLd202rbd5dHRZZDyddXE+WEfjBHB1kPLqQuxPHG+iCx0+d0iATAaG3BFIwjA7dQfNGKO5Lhn302J885eSh8UPK2kV4EXEXtniWbWGKi+NLWb6LFbe8UKKTPfF2e/AYxj5NndsZ4kIPhPfRWPech6/OrX5RsdewYCKE8HNv0boE592DhW8PQPWLnzqlQkUpIFS2cpdnm8IeB53/3IP3LbuZ+ZAFx25yLJMrNGRreFImoEHQEfV9RcbSQmNGOZbSzhgMNT9g3tDb8USBhu/33pXMPeyFLwkhJCDnyk3Gbzd18tkBkDx9sM9/OBg51BcwWCY/Og7QIMhkQz7Tc/W3KyRUY27MLaOk9ZWP0d/WBZgC0ey0XgdijZtYZp0Tyh1AjZplygttJT5kpmZltkypihx2+jVeau/W/2njVkxj7oJLXWdnb1FTIMidjXocyK+gtwq76oS5hZr9Xrt54bngmtKBDRIRAINwksiGzk=
    - AWS_DEFAULT_REGION=us-east-1
    # travis encrypt DOCKER_REGISTRY_ID=<registry_id>
    - secure: XmADTlTw9W8UBzibpQWJcilabzcAIgV8ywtyyucS8iKsdURyJ5u8KqgR9dOLsacagckxs+FeHISGah1FITx+Bi4M4p9erMdjjIj+vNxmdGmUExj2iCN3P4/jGfBRUa+oGpRozAQpPH68YYNLrE53kC5ffFWx8f+LtxExWdblW4vI9I/MwpWt0ocdNKNWX+fdXEZ2OnzFmuqM+zJ2z7wx4qFreoOcnAxzf93I0huw2HffsuB/k48q1OgmLW7lJWo/YDNo0c3bipb7ZTw8IralbnhyA746QGNnilXsSmJo3My12WpTUl4YsiZexmJunAkLtj0N/azqTB467rcxTnBKtW2JSD8GLPo9BkPVeApjHIe7WUwrpW7WrwaoEnnmcs75RPdOJTEinUmSbMrR9HX0KoQYw+x6QTAslYhcrmUfzjVgRAtkA1xhwQZq0LV6OPWJGbTPNzxaWzxdETPsNnVEVx/VXM61s83Z2kfDozv68hh8MhFJs4D+8DEijukma4ZIcGnMZwSSgctVlUb9rqyjgL3qpHEuCT5E+cbTa+61w9Bd5SU+hOCWLdVja3baBjTrRv9CRkA1HotztTqswWtheO4BqD97Tvc41PyGTvAQqDdurspq0bvYWbYxBRB3XjHLVG5/6zvXqQBrx2J1UjwJUrbKuXPh+D1gOjSQcwE1XAA=

notifications:
  slack:
    rooms:
      - intentmedia:SrPsBbiyUmm6V0ZMEFIB6RWG
    on_success: never
    on_failure: never
  on:
    branch: master

before_install:
  - pip install awscli

script:
  - ./build.sh build

deploy:
  skip_cleanup: true
  provider: script
  script: "./build.sh deploy"
  on:
    branch: master