language: python
python:
- 3.7-dev
services:
- docker
env:
  global:
  - AWS_ACCESS_KEY_ID=AKIA4TXB7QOHCEQQJU5V
  - AWS_DEFAULT_REGION=us-east-1
  - secure: He5YbmNB2atsX65EcLCAvDwYt6N9ax3HldZhqYjqrVpNQbVZ6NFQtbIIufo20ieZBRiMfyKJ+iA3XMhuShJ5U+bxFbHkZ3rJvSABg4EoSGUAaYU+YKkWg36axEWcGW3YchlRH9d0ACEafvvw1XvwbU9sxR1ZNM2auQHguVPY5mZFSJAZpFMLmtgOZ+gN/RlaKdRABas1mO3WaXLBMTEKa4iuLvH+04j4oTMQiYoTQZQXCNgOJtArT69JbweCI7nJynz6QDS3YKNwIXaBGJV1pS2FGZvrHHaO5hzd8uQtO4hUANHplmhyebbiy595TNVQhDJ514Ifmrq4fktIpHlc2zKqDfzKACZyoV6cccEGbGAH+EGcC56RRWSG5o3bcMGCFgt0Ku9uePsIvzwMpHgIInrcXwhP7GBytGELgKhF0RF/GSy6xcfSh1VAPnL/PWAshdak8m6ePIkzf8EzWc14HN79eLj3DHR4c98AqxARLlolbGJIyU507D5HJFD73E0JQl6zOYhkk7pxm1boYzJKc12AUYOowBs7aV4UyMpxuBOCr45KJit6VPUrqXzRFYDD6fa1iCQqiHEU4V1/RZ2o1Dxh5uIeVP8NW/VhRy96J0PDMB9J0PMb/gyBETSE70sJ/XjGQVsRvTrhd0DllWJW7UWwl3zNJ5w8pPmy3YczS8A=
notifications:
  slack:
    rooms:
    - intentmedia:SrPsBbiyUmm6V0ZMEFIB6RWG
    on_success: never
    on_failure: never
  on:
    branch: master
before_install:
- pip install awscli
script:
- "./build.sh build"
deploy:
  skip_cleanup: true
  provider: script
  script: "./build.sh deploy"
  on:
    branch: master
