language: python

python:
  - "3.7-dev"

services:
  - docker

env:
  global:
    #Production aws key
#    - AWS_ACCESS_KEY_ID=AKIA4TXB7QOHHZS3P4PE
    #Production secret key: travis encrypt AWS_SECRET_ACCESS_KEY=<SECRET_KEY>
#    - secure: FU01bHKyorPLnpzHrzPrtJv4vbgNHpMDxBieU9GUN/FE4/xvT6pndYLVf1yxAdq/BWSTTH3e8MKfmGXSNLL4ZlvPizzv2/fmJMOf9IzOmuP4QQgdfed6Qjwykd6yygd/nKusjOYH7z+ypWveYwqvhyDejgVSyuP/vaI2gYGNGbec+GbH2Vg633m3zNf1z9G8LBK0X5uJwDTvPdtTXRLHUICsMrL9FmAavwweW6yvTOrfqfqG2CEAucF8sUkZmnpcaI72pYmTbIJQhDyPi5qbMDa9lbnA2OB6pvgwyPf4IYxBQACO+iZMpYoyv6pJ4gq03FgjRIKDc2kXZAUsKRwq9iEhNlXWkDPmvzrbilAMS9WYwP+GyBsTTcC+HtI8Kwhioq2IFFF9yGZSYp7n4g5sV7dLmNJvbjYBlZm7KcFg0rogLmEw1yJZYNFLoAFxMfDtX0S1yeMR+ntNAfMey/DppcXdMNs/hIbvWtl6PqJLQ58N9KRijirKW+U8ikMLxx+C4SYjGLpwHRhKDbkGlKeV06jOu0gPshDdnIbR+fFu0IvzIHw9tv+usRMcj7K2YezCtQ2wCRLKbZEAlFU+GRaTpZZDRKO2SB5U8y/zWc4cYh27CI46JYB/gpA2HesJSJJfQOTg6WiZjQjoxcSUOFfnNjZMy8gWevUGuo/HzpNPFAc=
    - AWS_DEFAULT_REGION=us-east-1
    # travis encrypt DOCKER_REGISTRY_ID=<registry_id>
#    - secure: x6OH3SkTJwVMFbeDaGoJ2FUCiNWL1dwemS/QNCvz8sUdeyxybtHJ5vy853paWtUsx9yADdIx8WnHhM+cUztD9fZlpE9BbRnvrQYk7hw8pcQgmL68pjPsF8tHwZxCuWd8hGw2KdJ4j1jJ3AwMO0+mAddKVc/SeKZEt8ASlQkFGyYRnO4GB01BXWSKMRR8pajxzcBMVXCrXX9zk9cjg6giAmt5OxyshFfAiEtKf4Ht4tjnA29AQ992Qsc+8YWFRHF1AHPCfXmtSQxYKenU4SHLUilZRbnTSqEhfaAiYWK9gDzWbg+I+E8SPyVTtRRGq7d7Vj3oMKLNM8Ap5851JXnPKLMKvaMoU1XnJdFBSrFwFiEUhG/pQZ7MOFwMk/1jpX+QTtlMWY3Kl4bTXr6NYibJXoH09avXGZvpyHmA95Wh83lHtd7AJyR+RjDtXfgHohkki8RRbYXkqxIrAuFVnYr1QQj51pbfryhqrb0ACIZocc14nn1pru6z95MueAGXZ50CMeuANJQTxFrxzlntE2VwK5Geu3G/bmYofQbcOLuOFD9D7pyauIgTbXi5Bbu2gBH+G8GE+DyJBQ70RozlF3oFJN9JoLDrp1x3yns9Q6lRyvOhNp+6f25Lmz52J+qVVjfQBKSE3CItsqAvmfT3dYFzbrdYNPS2c2H8tFpPrfdUhDA=

notifications:
  slack:
    rooms:
      - intentmedia:SrPsBbiyUmm6V0ZMEFIB6RWG
    on_success: never
    on_failure: never
  on:
    branch: master

before_install:
  - pip install awscli

script:

deploy:
  skip_cleanup: true
  provider: script
  script: "./build.sh deploy"
  on:
    branch: master