language: python
python:
- 3.7-dev
services:
- docker
env:
  global:
  - AWS_ACCESS_KEY_ID=AKIA4TXB7QOHCEQQJU5V
  - AWS_DEFAULT_REGION=us-east-1
  - secure: He5YbmNB2atsX65EcLCAvDwYt6N9ax3HldZhqYjqrVpNQbVZ6NFQtbIIufo20ieZBRiMfyKJ+iA3XMhuShJ5U+bxFbHkZ3rJvSABg4EoSGUAaYU+YKkWg36axEWcGW3YchlRH9d0ACEafvvw1XvwbU9sxR1ZNM2auQHguVPY5mZFSJAZpFMLmtgOZ+gN/RlaKdRABas1mO3WaXLBMTEKa4iuLvH+04j4oTMQiYoTQZQXCNgOJtArT69JbweCI7nJynz6QDS3YKNwIXaBGJV1pS2FGZvrHHaO5hzd8uQtO4hUANHplmhyebbiy595TNVQhDJ514Ifmrq4fktIpHlc2zKqDfzKACZyoV6cccEGbGAH+EGcC56RRWSG5o3bcMGCFgt0Ku9uePsIvzwMpHgIInrcXwhP7GBytGELgKhF0RF/GSy6xcfSh1VAPnL/PWAshdak8m6ePIkzf8EzWc14HN79eLj3DHR4c98AqxARLlolbGJIyU507D5HJFD73E0JQl6zOYhkk7pxm1boYzJKc12AUYOowBs7aV4UyMpxuBOCr45KJit6VPUrqXzRFYDD6fa1iCQqiHEU4V1/RZ2o1Dxh5uIeVP8NW/VhRy96J0PDMB9J0PMb/gyBETSE70sJ/XjGQVsRvTrhd0DllWJW7UWwl3zNJ5w8pPmy3YczS8A=
  - secure: aAgdy+Ib5ET7Ez1DKJDZzFIEjva0K/34Or9/r7SDKo6rvviCRXgd/0dvMUG/2TaJR4kz/yNvB0UTJn1A0Yyvp4HVKfTZDW0w0o+RiJyrj4ZBZBvbSgCbg94+yX/FsjuZHtwbq/93N7hR0E2MVYZ5h/KpARzS2lxlwyzjTfb6NMvGFLXDSg/4vFpdjnXkrdoZyxvD1pHrTO8eaJLP1/OND+iLY0wJ/apo7heRV/j7gD6OlucRVjWNe5D/qPR0iac5wv7wdtSYwFwNF4QaBXRk9bBEDwMCimtHkAU6IwO9if7otHR4725emi9u2HnCKi6iUSziuTBJQO0S0tQOVnfVdmB0HHwDCubt+VWYZkYmO+PnMzB+obttWZfZ4vsHIyqBHf12UCUJgNBObLGlhxuAiBh7KNv52fyPZMqRRYTqYlBOcnz1YEoFOyC4w4yslYjjZmFv2TVx5cZlL2ig2jqJLxyToEtXrOqND4fAgRfFG4jdAOu8dEqaI0bW6zgal+eSl7Kz3Kl60Pkoz6fwUQr9VP8Zh8Z3RvnksDjTWluiDo7kl6D4/OUVDT5AerRG6CQlBkXRHu8hKxaYIxJvsp7H15WxnCmQpslTtR3hiU5JjmQRkOQNEJggrSlvRS8YB7dh9erX9lPXYGvdsBSBdlFReeAPQwv2pLw2z4UyQibBYOA=
notifications:
  slack:
    rooms:
    - intentmedia:SrPsBbiyUmm6V0ZMEFIB6RWG
    on_success: never
    on_failure: never
  on:
    branch: master
before_install:
- pip install awscli
script:
- "./build.sh build"
deploy:
  skip_cleanup: true
  provider: script
  script: "./build.sh deploy"
  on:
    branch: master
