language: python

python:
  - "3.7-dev"

services:
  - docker

env:
  global:
    #Production aws key
    - AWS_ACCESS_KEY_ID=AKIA4TXB7QOHH4GTVXZF
    #Production secret key: travis encrypt AWS_SECRET_ACCESS_KEY=<SECRET_KEY>
    - secure: wX9GxWCKjr0tjj1y8HfVZBTxdS6+e0QMzqBQu8wh+KkJvWWwTptCcUr9iqMZRnWxNWeYb2oIlNP2ilOfE8f60kxM6svZ2Fn9AEahSOzFJSuXaLqJBb0UPrjYOswnnk2vPKUw7zgVabCH/kev5O4WRV8Dit0b5o+QRSGMBR9eIf9X1zXq2HPPbZylgzxzpql+VoF1w3UAXyrN2e9XfPYaqmBHhTShVf/YB5Egrx32VNRE1EhmM8ie163kPsiOWFwZE7Ty0wPOshpXcpjVwC6R3O/Cm1/Yh5qQXFxTA/mQ8ntgjfU8u0Mq7zVyTUc2hIFwBDASBTF1hJ+Xvcl5FMZWU5bGDVmAp9pEkUKrwCERMQSWyEl/Em69s3to0qcxTkposAEYrw0WtZ1Jo/b6Vwr4IVB9FKnCb/xkwuKVtpbHM7038F+XQb818f+T26DEj1izW8zvJ6v1lYjzj8+u8amW384YfstEBG8SNsMlMTmcXhTA2NPsQK8Suz0jHhd4wGpmlfufDNDUXA3bsdgMxVsgRhH5DelgHATzwWIiMkCcYmc//gW8BEDZNVYD/qmnQu1bH9Vg9In7QqVScR/gOjUo7yLdOhBYXUnX9h2qX3SSvoYNbDXCzagzbkNEis1uPk3fQrur62FdVLMu3Ja1pJDetQZCsqZd7Ixekb8LY0GDo6w=
    - AWS_DEFAULT_REGION=us-east-1
    # travis encrypt DOCKER_REGISTRY_ID=<registry_id>
    - secure: XmADTlTw9W8UBzibpQWJcilabzcAIgV8ywtyyucS8iKsdURyJ5u8KqgR9dOLsacagckxs+FeHISGah1FITx+Bi4M4p9erMdjjIj+vNxmdGmUExj2iCN3P4/jGfBRUa+oGpRozAQpPH68YYNLrE53kC5ffFWx8f+LtxExWdblW4vI9I/MwpWt0ocdNKNWX+fdXEZ2OnzFmuqM+zJ2z7wx4qFreoOcnAxzf93I0huw2HffsuB/k48q1OgmLW7lJWo/YDNo0c3bipb7ZTw8IralbnhyA746QGNnilXsSmJo3My12WpTUl4YsiZexmJunAkLtj0N/azqTB467rcxTnBKtW2JSD8GLPo9BkPVeApjHIe7WUwrpW7WrwaoEnnmcs75RPdOJTEinUmSbMrR9HX0KoQYw+x6QTAslYhcrmUfzjVgRAtkA1xhwQZq0LV6OPWJGbTPNzxaWzxdETPsNnVEVx/VXM61s83Z2kfDozv68hh8MhFJs4D+8DEijukma4ZIcGnMZwSSgctVlUb9rqyjgL3qpHEuCT5E+cbTa+61w9Bd5SU+hOCWLdVja3baBjTrRv9CRkA1HotztTqswWtheO4BqD97Tvc41PyGTvAQqDdurspq0bvYWbYxBRB3XjHLVG5/6zvXqQBrx2J1UjwJUrbKuXPh+D1gOjSQcwE1XAA=

notifications:
  slack:
    rooms:
      - intentmedia:SrPsBbiyUmm6V0ZMEFIB6RWG
    on_success: never
    on_failure: never
  on:
    branch: master

before_install:
  - pip install awscli

script:
  - ./build.sh build

deploy:
  skip_cleanup: true
  provider: script
  script: "./build.sh deploy"
  on:
    branch: master